name: Profile Readme Updater

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow workflow to write to repository contents
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      - name: Generate GitHub Stats
        run: python .github/scripts/update_stats.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
# Temporarily disabled due to Exit code 128
#      - name: Update Recent Activity
#        uses: jamesgeorge007/github-activity-readme@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Removed Snake Generation step as it's no longer used
      # - name: Generate Snake Animation
      #   uses: Platane/snk@master
      #   id: snake-gif
      #   with:
      #     github_user_name: FutureAtoms
      #     svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Update Timestamp in README
        run: |
          sed -i "s|<!-- LAST_UPDATED -->|<!-- LAST_UPDATED: $(date) -->|g" README.md
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md # Only add README.md
          # Commit changes with the current date, allowing empty commits
          git commit --allow-empty -m "Update profile README - $(date)"
          git push
